#!/usr/bin/env python3
"""
Script to generate a mostly blank HTML file with the current date as the title.
This script is designed to be called by a GitHub Action on a cron schedule.
"""

import os
from datetime import datetime
from pathlib import Path

def generate_html_with_date():
    """Generate an HTML file with the current date as the title."""
    
    # Get current date in a readable format
    current_date = datetime.now().strftime("%Y-%m-%d")
    
    # Create the website directory if it doesn't exist
    website_dir = Path("./website")
    website_dir.mkdir(exist_ok=True)
    
    # Generate HTML content
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{current_date}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 800px;
            margin: 0 auto;
            background-color: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #333;
            text-align: center;
            margin-bottom: 30px;
        }}
        .date-info {{
            text-align: center;
            color: #666;
            font-size: 18px;
            margin-bottom: 20px;
        }}
        .content {{
            color: #444;
            line-height: 1.6;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Generated Page</h1>
        <div class="date-info">
            Generated on: {current_date}
        </div>
        <div class="content">
            <p>This is a mostly blank HTML file generated by a GitHub Action cron job.</p>
            <p>The page was created on {current_date}.</p>
        </div>
    </div>
</body>
</html>"""
    
    # Write the HTML file
    output_file = website_dir / f"index_{current_date}.html"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f"Generated HTML file: {output_file}")
    print(f"Title: {current_date}")

if __name__ == "__main__":
    generate_html_with_date() 