name: Telegram Chat Verification

on:
  schedule:
    # Run daily at 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  verify-telegram-chats:
    runs-on: ubuntu-latest
    environment: test
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Verify Telegram chats
      env:
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
      run: python scripts/fetch_telegram_chats.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./website/
        git add chat_ids.yaml
        git commit -m "Telegram chat verification report $(date +%Y-%m-%d)" || echo "No changes to commit"
        git push 